vim.g.neovide_hide_mouse_when_typing = true
-- vim.g.neovide_refresh_rate = 144
vim.g.neovide_remember_window_size = true
vim.g.neovide_cursor_animation_length = 0.03
-- vim.g.neovide_cursor_trail_size = 0.5
-- vim.g.neovide_scroll_animation_length = 0.9
vim.g.neovide_cursor_animate_in_insert_mode = true
vim.g.neovide_cursor_animate_command_line = true
vim.g.neovide_cursor_unfocused_outline_width = 0.125
